use_frameworks!

platform :ios, '8.0'

target 'DZGSVGAPlayerModule_Example' do
  pod 'DZGSVGAPlayerModule', :path => '../'

  target 'DZGSVGAPlayerModule_Tests' do
    inherit! :search_paths

    
  end
end
